Add PHP 8-only support (v2)
spatie/regex pull request #55
Opened 2021-03-28 15:51 UTC by patinthehat

This PR adds a new major version, v2.0.0.

Specifically, it:

- Removes support for all PHP 7.x versions.
- Requires PHP 8.0+.
- All syntax converted to PHP 8 where possible.
- Removes unnecessary PHP docblocks per Spatie's guidelines.
- Moves exception classes to an "Exceptions" directory to match the structure of other packages.
- Adds config & github workflow for `php-cs-fixer`.
- Updates the location of `CONTRIBUTING.md`.
- Updates the readme with minor adjustments from [spatie/package-skeleton-php](https://github.com/spatie/package-skeleton-php).
- _Updates the changelog - release date needs to be updated, currently is "unreleased"._

2021-03-28 16:28 UTC, freekmurze requested changes

2021-03-28 16:28 UTC, freekmurze commented on .php_cs.cache
> +{"php":"8.0.3","version":"2.18.3","indent":"    ","lineEnding":"\n","rules":{"blank_line_after_namespace":true,"braces":true,"class_definition":true,"constant_case":true,"elseif":true,"function_decla
This file should not be included in the PR.

2021-03-28 16:28 UTC, freekmurze commented on src/MatchAllResult.php
> +    public function __construct(
Nice!

2021-03-28 16:28 UTC, freekmurze commented on src/MatchResult.php
> +    public function result(): string | null
`?string` might be nicer to use.

2021-03-31 14:17 UTC, patinthehat commented
ping @freekmurze

2021-03-31 14:24 UTC, merged

2021-03-31 14:24 UTC, freekmurze commented
Thanks!